import { index, integer, pgTable, text, timestamp, vector } from "drizzle-orm/pg-core";

export const comic = pgTable(
  "comic",
  {
    number: integer().primaryKey(),
    title: text().notNull(),
    imgUrl: text().notNull(),
    alt: text().notNull(),
    /** Either official transcript, or generated by AI */
    transcript: text().notNull(),
    /** Generated by AI */
    explaination: text().notNull(),
    transcriptEmbedding: vector({ dimensions: 1536 }),
    explainationEmbedding: vector({ dimensions: 1536 }),

    indexedAt: timestamp().defaultNow().notNull(),
    publishedAt: timestamp().notNull(),
  },
  t => [
    index("transcriptEmbeddingIndex").using("hnsw", t.transcriptEmbedding.op("vector_cosine_ops")),
    index("explainationEmbeddingIndex").using("hnsw", t.explainationEmbedding.op("vector_cosine_ops")),
    index("publishedAtIndex").using("btree", t.publishedAt),
  ]
);
